### ISSUE TITLE
Validate CSGO authentication info

### ISSUE THREAD

**Issue by emielvanseveren** [Bantr/Koyi#29]
When auth info is outdated, it should be flagged as such in the DB

**Comment by emielvanseveren** [comment]
@niekcandaele

**Comment by niekcandaele** [comment]
Edited the issue, API routes go in a different repo :smile: 

This issue should be easy, the actual route not so much. If you are worried about users entering invalid info, the two fields have a different structure. We can validate based on regex and that should weed out a lot of mistakes

**Comment by niekcandaele** [comment]
I think it's probably best we add this to the matchmaking parsing. If matchmaking parsing fails because auth info is invalid, we set a flag in the database. This  way the frontend can look for this flag and display an appropriate message


Blocked by https://github.com/Bantr/Koyi/issues/29

**Comment by niekcandaele** [comment]
Gonna close this one because [the other issue](https://github.com/Bantr/Koyi/issues/34) has better explanation of what needs to happen (woops :smile:)
